(function(e){var g=window.AmazonUIPageJS||window.P,l=g._namespace||g.attributeErrors,a=l?l("PREXWebAppBuzzAssets@common","PREXWebApp"):g;a.guardFatal?a.guardFatal(e)(a,window):a.execute(function(){e(a,window)})})(function(e,g,l){e.when("A","csm-publisher","csrf-utils","prex-event-batch-size-and-interval","url-utils").register("prex-event-batch-publisher",function(a,b,d,c,f){function k(c,k,h){var q={},e=a.state("returnContext");e&&e.returnSessionId&&(q={returnSessionId:e.returnSessionId});c=f.getUrlWithQueryParamsWithoutDuplicates(c,
q);a.post(c,{headers:d.addCsrfHeader({}),contentType:"application/json; charset\x3dutf-8",paramsFormat:"json",params:JSON.stringify(k),success:function(){b.addCsmCount("PREX:Event:Batch:Publish:Error",0);h&&h()},error:function(){b.addCsmCount("PREX:Event:Batch:Publish:Error",1);h&&h()}})}function h(){p.length&&(k("/spr/returns/publishPREXEventBatch",p),p=[])}function q(){m.length&&(k("/spr/returns/publishPREXEventsGroupBatch",m),m=[])}function e(){q();h();t=!1}function u(){!t&&l&&(t=!0,a.delay(e,
1E3*l))}var n=c.size?c.size:1,l=c.interval?c.interval:0,p=[],m=[],t=!1;g.onbeforeunload=e;return{publishEvent:function(b){p.push(b);u();p.length===n&&h()},publishEventsGroup:function(b,a){a?k("/spr/returns/publishPREXEventsGroupBatch",[b],a):(m.push(b),u(),m.length===n&&q())}}});"use strict";e.register("prex-event-batch-size-and-interval",function(){return{size:1}});"use strict";e.when("A").register("auto-scroll-utils",function(a){function b(b,c){c=c?c:600;a.$("html, body").animate({scrollTop:b},
c)}return{scrollToElementById:function(d,c){(d=a.$(d))&&b(d.offset().top,c)},scrollToElementByOffset:b,scrollToPageTop:function(a){b(0,a)},scrollHorizontallyToCenterOfElement:function(b,c){if(!(b&&b.length&&c&&c.length)||a.capabilities.rtl)return!1;var f=c.position().left;c=c.outerWidth(!0);f+=c/2;c=b.width();b.animate({scrollLeft:Math.floor(f-c/2)});return!0}}});"use strict";e.when("A").register("background-scroll-utils",function(a){return{disableScrollOfBackground:function(){a.$("html").css({overflow:"hidden"});
a.$("body").css({overflow:"hidden"})},enableScrollOfBackground:function(){a.$("html").css({overflow:"auto"});a.$("body").css({overflow:"auto"})}}});"use strict";e.when("A","a-button").register("button-utils",function(a,b){return{disableButton:function(a){b("#"+a).disable()},enableButton:function(a){b("#"+a).enable()},disableButtonByClass:function(a){b("."+a).disable()},enableButtonByClass:function(a){b("."+a).enable()},isButtonEnabled:function(a){return b("#"+a).isEnabled()}}});"use strict";e.when("A",
"csm-publisher","ready").register("capture-time-stamp",function(a,b){return{forCounter:function(a){return{endTimer:function(){b.captureEndTimeStampAndSendToServer(a)},startTimer:function(){b.captureStartTimeStamp(a)}}}}});"use strict";e.when("A","a-checkbox").register("checkbox-utils",function(a,b){return{isChecked:function(d){return a.$("#"+d).length&&(d=b("#"+d),null!==d)?d.isChecked():!0},isInstanceChecked:function(a){a=b(a);if(null!==a)return a.isChecked()}}});"use strict";e.when("A","a-button",
"ready").register("continue-button-handler",function(a,b){function d(b){a.$("#"+b._$coreFormElement[0].dataset.formId).submit()}function c(a){b("#"+a).enable()}function f(a){b("#"+a).disable()}return{submitAssociatedForm:function(a){a=b("#"+a);d(a)},handleContinueButtonClick:function(a){a=b("#"+a);a.isEnabled()&&d(a)},enableButton:c,disableButton:f,removeFocus:function(b){a.$("#"+b).removeClass("a-button-focus")},setState:function(b,a){b?c(a):f(a)}}});"use strict";e.when("A","ready").register("csm-publisher",
function(a){function b(b,a){var f=g.ue;f&&f.count&&f.count(b,a)}return{incrementCsmCount:function(a){a&&b(a,1)},addCsmCount:b,captureStartTimeStamp:function(a){var b=g.uet;"function"===typeof b&&b("bb",a,{wb:1})},captureEndTimeStampAndSendToServer:function(a){var b=g.uex;"function"===typeof b&&b("ld",a,{wb:1})},getCSMPublisherPrefix:function(){return"PLS"===a.$("#workflowType").val()?"PREX:PLS":"PREX:SPR"}}});"use strict";e.when("A","csm-publisher","prex-logger").register("csrf-utils",function(a,
b,d){function c(){var b="";try{b=a.$("meta[name\x3dprex-csrf-token-meta]").attr("content")}catch(c){throw new TypeError("CSRF Token not present in the DOM");}if(b===l||null===b||""===b)throw new TypeError("CSRF Token not present in the DOM");return b}function f(a){var c=b.getCSMPublisherPrefix()+":CSRF:TokenAbsent";b.addCsmCount(c,a)}function k(a){var c=b.getCSMPublisherPrefix()+":CSRF:TokenRetrievalError";b.addCsmCount(c,a)}return{addCsrfHeader:function(b){try{b["anti-csrftoken-a2z"]=c(),f(0),k(0)}catch(a){"TypeError"===
a.name&&"CSRF Token not present in the DOM"===a.message?f(1):k(1)}return b},getRedirectUrlForInvalidCsrf:function(a){try{if(a&&a.http){var c=a.http.getResponseHeader("location");if(403===a.http.status&&c!==l&&null!==c&&-1!==c.indexOf("prex-invalid-csrf"))return c}}catch(f){b.addCsmCount("PREXWebApp:CSRF:RedirectError",1),d.error("Error: "+f.name+" fetching redirect url for csrf with message: "+f.message)}},getCsrfToken:c}});"use strict";e.when("A","csrf-utils","csm-publisher").register("customer-event-publisher",
function(a,b,d){function c(c,e){var g=c,n=JSON.parse(atob(c)).pageType;e!==l&&(g+=encodeURIComponent(e));0<=a.$.inArray(g,h)||(h.push(g),a.post(k(n),{headers:b.addCsrfHeader({}),params:f(c,e),error:function(a){n&&"ProductLifecycleSupport"===n?d.incrementCsmCount("PREX:FailedToPublishPLSCustomerEvent"):d.incrementCsmCount("PREX:FailedToPublishORCCustomerEvent")}}))}function f(a,b,c){a={customerEventAttributes:a,eventGenerationTimestamp:(new Date).getTime(),isResolutionsV2:!!c};b!==l&&(a.eventData=
encodeURIComponent(b));return a}function k(a){return a&&"ProductLifecycleSupport"===a?"/ps/product-support/customer-event":"/spr/returns/customer-event"}var h=[];return{publish:c,publishForPageType:function(b,f,d){f=JSON.parse(atob(f));a.$.extend(f,b);f=btoa(JSON.stringify(f));c(f,d)},publishEventV2:function(c){if(!(0<=a.$.inArray(c,h))){var e=JSON.parse(c).pageType,e=k(e);h.push(c);a.post(e,{headers:b.addCsrfHeader({}),params:f(c,l,!0),error:function(a){d.incrementCsmCount("PREX:FailedToPublishORCCustomerEvent:V2")}})}}}});
"use strict";e.when("A","customer-event-publisher","ready").register("click-customer-event-publisher",function(a,b){a.$("body").delegate(".click-customer-event","click",function(){var d=a.$(this).data("customerEventAttributes");b.publish(d)})});"use strict";e.when("A","customer-event-publisher","ready").register("page-load-customer-event-publisher",function(a,b){a.$(".page-load-customer-event").each(function(){var d=a.$(this).data("customerEventAttributes");b.publish(d)})});"use strict";e.when("A",
"csm-publisher","prex-logger","ready").register("dhl-links-metric-utils",function(a,b,d){function c(a,c,f){return b.getCSMPublisherPrefix()+":"+a+":"+c+":"+f.fromCountryCode.toLowerCase()+":"+f.languageCode.toLowerCase()}var f=b.getCSMPublisherPrefix()+":dhlLink:metricError";return{registerDhlLinkClickEventHandlers:function(k){a.$("a[href\x3d'https://locator.dhl.com/']").bind("click."+k,function(){a.$(this).attr("href");try{var h=c(k,"dhlLink:dropOff",{fromCountryCode:"",languageCode:""});b.incrementCsmCount(h)}catch(e){d.error(e,
"dhl-links-metric-utils");try{b.incrementCsmCount(f)}catch(g){d.error(g,"dhl-links-metric-utils")}}});a.$("a[href^\x3d'https://mydhl.express.dhl/'][href*\x3d'/schedulePickupTab'], a[href^\x3d'https://mydhl.express.dhl/'][href*\x3d'/createNewShipmentTab']").bind("click."+k,function(){var h=a.$(this).attr("href");try{var e;e={fromCountryCode:h.match(/mydhl\.express\.dhl\/([a-z]{2})\/[a-z]{2}\/home.html#\/(schedulePickupTab|createNewShipmentTab)/i)[1],languageCode:h.match(/mydhl\.express\.dhl\/[a-z]{2}\/([a-z]{2})\/home.html#\/(schedulePickupTab|createNewShipmentTab)/i)[1]};
var g=c(k,"dhlLink:pickup",e);b.incrementCsmCount(g)}catch(l){d.error(l,"dhl-links-metric-utils");try{b.incrementCsmCount(f)}catch(n){d.error(n,"dhl-links-metric-utils")}}})},unregisterDhlLinkClickEventHandlers:function(b){a.$("a[href\x3d'https://locator.dhl.com/']").unbind("click."+b);a.$("a[href^\x3d'https://mydhl.express.dhl/'][href*\x3d'/schedulePickupTab'], a[href^\x3d'https://mydhl.express.dhl/'][href*\x3d'/createNewShipmentTab']").unbind("click."+b)}}});"use strict";e.when("A","ready").execute(function(a){a.$("body").delegate(".no-copy-paste",
"cut copy paste",function(a){a.preventDefault()})});"use strict";e.when("A","ready").register("display-utils",function(a){function b(b){a.$("#"+b).addClass(a.constants.HIDE_CLASS)}function d(b){a.$("#"+b).removeClass(a.constants.HIDE_CLASS)}function c(b){return!b.hasClass(a.constants.HIDE_CLASS)}return{hideElementById:b,showElementById:d,setElementVisibilityById:function(a,c){c?d(a):b(a)},hideElementsByClassName:function(b){a.$("."+b).addClass(a.constants.HIDE_CLASS)},showElementsByClassName:function(b){a.$("."+
b).removeClass(a.constants.HIDE_CLASS)},isElementForIdVisible:function(b){return c(a.$("#"+b))},isElementVisible:c,isElementForIdHidden:function(b){return a.$("#"+b).hasClass(a.constants.HIDE_CLASS)}}});"use strict";e.when("A","a-dropdown").register("dropdown-utils",function(a,b){function d(b){return a.$.map(b,function(b){return{text:b,value:b}})}function c(b){for(var a=[],c=0;c<b;c++)a.push(c);return a}return{addOptionsToDropdown:function(a,c){b.getSelect(a).addOptions(d(c))},removeAllOptionsFromDropdown:function(a){a=
b.getSelect(a);var d=a.getOptions().size();a.removeOption(c(d))},isValidDropdownValue:function(a){return a&&""!==a},getSelectedDropdownOption:function(a){if(null!==b.getSelect(a))return b.getSelect(a).getOptions().info().find(function(a){return a.selected})}}});"use strict";e.when("A").register("error-display-utils",function(a){return{highlightElementById:function(b){a.$("#"+b).addClass("orc-form-error")},highlightElementByCssClass:function(b){a.$("."+b).addClass("orc-form-error")},unhighlightElementById:function(b){a.$("#"+
b).removeClass("orc-form-error")},unhighlightElementByCssClass:function(b){a.$("."+b).removeClass("orc-form-error")}}});"use strict";e.register("geolocation-position-error",function(){return{PERMISSION_DENIED:{code:1,message:"User denied Geolocation"},POSITION_UNAVAILABLE:{code:2,message:"Position unavailable"},TIMEOUT:{code:3,message:"Timeout acquiring position"},UNKNOWN_ERROR:{code:l,message:"Unknown error acquiring position"}}});"use strict";e.when("A").register("items-details-modal-utils",function(a){function b(b){for(var c=
b.$container.find(".modal-content").find(".images-row").filter(function(b,c){return 0===a.$(c).closest(".aok-hidden").length}),f=Math.min(c.size(),3),e=0,h=0;h<f;h++)e+=a.$(c[h]).outerHeight(!0);b=b.$container.find(".a-popover-header-content").outerHeight(!0);return e+75+b}return{initModalWithMaxHeight:function(d){a.on("a:popover:afterShow:"+d,function(a){a=a.popover;var d=b(a);a.update({height:d}).lock().show()})}}});"use strict";e.when("a-modal").register("modal-utils",function(a){return{updatePosition:function(b){(b=
a.get(b))&&b.updatePosition()},hide:function(b){(b=a.get(b))&&b.hide()},remove:function(b){(b=a.get(b))&&b.$container&&b.$container.remove()}}});"use strict";e.when("A").register("object-utils",function(a){return{isDefined:function(a){return null!==a&&"undefined"!==typeof a}}});"use strict";e.when("A","ready").register("page-state-utils",function(a){return{getPageStateData:function(b){a.state.parse();return a.state(b)},getValue:function(b,d){b=a.state(b);return b===l?null:b[d]}}});"use strict";e.when("A",
"display-utils","ready").register("pinning-utils",function(a,b){function d(a){r=!1;a.css({position:"absolute",left:""})}function c(a){clearInterval(v);v=setInterval(f,250,a)}function f(b){var c=a.$("#a-page").width();c!==y&&r?(w=!0,m.defaultPinLeft=b.offset().left,clearInterval(v)):r&&(w=!0,clearInterval(v));y=c}function e(b,c){c=a.$("#"+c).height();q(b,c)}function h(c,d){d=a.$("."+d+":visible").height();b.isElementForIdVisible(c)&&q(c,d)}function q(b,c){b=a.$("#"+b);var d=a.$(g),d={left:d.scrollLeft(),
top:d.scrollTop()};n===d.left||p?(c-=b.height(),0>c?(b.css({position:"absolute",top:"",left:"",width:m.pinWidth}),p=!0):d.top>c?(b.css({position:"absolute",top:c,left:"",width:m.pinWidth}),p=!0):(u(b,d),p=!1)):l(b,d)}function l(a,b){x||a.css({position:"absolute",top:a.offset().top-m.defaultPinTop,left:"",width:m.pinWidth});g.clearTimeout(x);x=g.setTimeout(function(){x=0;u(a,b)},100);n=b.left}function u(a,b){r&&w&&a.css({position:"fixed",top:m.defaultPinTop,left:m.defaultPinLeft-b.left,width:m.pinWidth})}
var n=0,x=0,p=!0,m,t,r=!0,v,y=0,w=!0;return{pinToClass:function(b,f){var e=a.$("#"+b);m={pinWidth:e.width(),defaultPinLeft:e.offset().left,defaultPinTop:a.$("."+f).offset().top};var k=a.$(g);k.scroll(a.debounce(function(){h(b,f)},5));k.resize(a.debounce(function(){r&&(d(e),c(e),w=!1);clearTimeout(t);t=a.delay(function(){r=!0;m.defaultPinLeft=e.offset().left;m.pinWidth=e.parent().width();e.css({width:m.pinWidth})},10)},10))},pinToId:function(b,c){var d=a.$(g),f=a.$("#"+b);m={pinWidth:f.width,defaultPinLeft:f.offset().left,
defaultPinTop:f.offset().top};d.scroll(a.debounce(function(){e(b,c)},5))},reAdjustPinLocationToClass:function(a,b){h(a,b)},adjustPinLocationToId:e}});"use strict";e.when("A","csm-publisher","csrf-utils","prex-event-batch-publisher","prex-event-publisher-status").register("prex-event-publisher",function(a,b,d,c,f){function e(a){return f.shouldAllowAllPages()?!0:-1!==(f.getAllowedPages()||[]).indexOf(a.subPageType)}return{publishEvent:function(d){d&&!a.$.isEmptyObject(d)&&e(d)?(b.incrementCsmCount("PREX:Event:Publish:Count"),
c.publishEvent(d)):b.incrementCsmCount("PREX:Event:Empty")},publishEventsGroup:function(a,d){a&&0!==a.length&&e(a[0])?(b.addCsmCount("PREX:EventsGroup:Publish:Count",a.length),c.publishEventsGroup(a,d)):(b.incrementCsmCount("PREX:EventsGroup:Empty"),d&&d())}}});"use strict";e.register("prex-event-publisher-status",function(){return{shouldAllowAllPages:function(){return!1},getAllowedPages:function(){return"SPRConfirmationPage SPRMethodsSectionPOST SPRLandingPageWithContract SPRLandingPage SPRBadDebtPage ProductSupportBrandChatPage".split(" ")}}});
"use strict";e.when("geolocation-position-error","csm-publisher").register("prex-location-service",function(a,b){function d(b,d,f){var e=function(){f(a.PERMISSION_DENIED)};if(c)c.permissions.requireForFeature({featureID:b.featureId,requestID:b.requestId}).onPermissionGranted(d).onPermissionDenied(e)}var c,f;e.now("mash","LocationService").execute(function(a,b){c=a;f=b});return{getCurrentPosition:function(a,e,g){if(c){var l=f&&f.createLocationManager("return_drop_off_location","return_drop_off_location_permissions");
f||b.incrementCsmCount("PREX:LocationServiceNotAvailable");l?c.permissions&&c.permissions.available?d(a,function(){l.getCurrentPosition({successCallback:e,failCallback:g})},g):g():(console.log("LocationManager not available"),b.incrementCsmCount("PREX:LocationManagerNotAvailable"))}else navigator&&navigator.geolocation&&navigator.geolocation.getCurrentPosition&&navigator.geolocation.getCurrentPosition(e,g)}}});"use strict";e.when("ready").register("prex-logger",function(){function a(a,d,c,f){if(g.ueLogError){var e=
g.ueLogError;c?a={logLevel:f,attribution:d,message:"["+a+"] "}:(c={message:"["+a+"]"},a={logLevel:f,attribution:d});e(c,a)}}return{warn:function(b,d,c){a(b,d,c,"WARN")},error:function(b,d,c){a(b,d,c,"ERROR")},fatal:function(b,d,c){a(b,d,c,"FATAL")}}});"use strict";e.when("A").register("text-area-utils",function(a){return{isTextAreaEmpty:function(b){if(a.$("#"+b).length)return 0===a.$("#"+b).val().trim().length},getText:function(b){if(a.$("#"+b).length)return a.$("#"+b).val().trim()}}});"use strict";
e.when("A","item-selection-utils","display-utils","summary-section-pinning-utils").execute(function(a,b,d,c){function e(){1===b.getNumOfItemsBeingReturned()&&(d.hideElementsByClassName("return-center-auxiliary-section"),d.showElementById("summary-section"),c.adjustLocation())}function g(){b.isAnyItemSelected()||(d.hideElementById("summary-section"),d.showElementsByClassName("return-center-auxiliary-section"))}0!==a.$("#return-center-page-content").length&&(a.on("cart:item:selected",e),a.on("cart:item:removed",
g))});"use strict";e.when("A","pinning-utils").register("summary-section-pinning-utils",function(a,b){var d=!1;return{pinToPageContainer:function(){!d&&0<a.$("#summary-section").length&&(b.pinToClass("summary-section","spr-page-primary-sections"),d=!0)},adjustLocation:function(){0<a.$("#summary-section").length&&b.reAdjustPinLocationToClass("summary-section","spr-page-primary-sections")}}});"use strict";e.when("A").register("url-utils",function(a){function b(a,b){return-1!==a.indexOf(b)}function d(b,
d){if(0===Object.keys(d).length)return b;d=a.$.param(d);return b+(/\?/.test(b)?"\x26":"?")+d}return{doesQueryParamAlreadyExist:b,getUrlWithQueryParams:d,getUrlWithQueryParamsWithoutDuplicates:function(a,e){var g={};Object.keys(e).forEach(function(d){b(a,d)||(g[d]=e[d])});return d(a,g)},extractParamFromQueryString:function(a,b){return(new g.URLSearchParams(a)).get(b)||""}}});"use strict";e.when("ready").register("redirection-utils",function(){return{setRedirectionUrl:function(a){g.location.href=a}}});
"use strict";e.when("A").register("rex-cache",function(a){return a.createClass({_cache:null,init:function(){this._cache={}},get:function(a){return a?this._cache[a]:null},put:function(a,d){a&&(this._cache[a]=d)}})});"use strict";e.when("a-secondary-view").register("secondary-view-utils",function(a){return{hide:function(b){(b=a.get(b))&&b.hide()},remove:function(b){(b=a.get(b))&&b.$container&&b.$container.remove()}}});"use strict";e.when("csm-publisher","prex-logger","ready").register("sorry-page-helper",
function(a,b){function d(a,b){a="/spr/returns/sorry?ref_\x3d"+a;b&&(a+="\x26prexDebug\x3d1");return a}return{redirectToSorryPage:function(c,e){var k=null;try{if(e&&-1!==e.http.getResponseHeader("content-type").indexOf("application/json")){var h=JSON.parse(e.http.response);h&&h.errorMessage&&(k={errorMessage:h.errorMessage})}}catch(l){a.incrementCsmCount("PREX:Ajax:DebugContentFetchFailed"),b.error("Exception getting debug content","ajax_debug_content",l)}(e=k)?(c=d(c,!0),g.history.pushState(e,null,
c),g.location.reload()):g.location.href=d(c,!1)}}});"use strict";e.when("prex-logger").register("mash-url-utils",function(a){return{goToUrl:function(b){a.error("Mash not supported on desktop! Invalid call to mash utils with url:"+b,"d_mash")}}});"use strict";e.when("A","a-modal").register("rex-modal-manager",function(a,b){var d={};return{show:function(a,e,g){var h=d[a];h?h.update({header:g.header}):(h=b.create(e,g),d[a]=h);h.show()},hide:function(a){(a=d[a])&&a.hide()},registerAfterHideListener:function(b,
d){a.on("a:popover:afterHide:"+b,d)}}});"use strict";e.when("ready").register("rex-logger",function(){function a(a,d,c,e){if(g.ueLogError){var k=g.ueLogError;c?a={logLevel:e,attribution:d,message:"["+a+"] "}:(c={message:"["+a+"]"},a={logLevel:e,attribution:d});k(c,a)}}return{warn:function(b,d,c){a(b,d,c,"WARN")},error:function(b,d,c){a(b,d,c,"ERROR")},fatal:function(b,d,c){a(b,d,c,"FATAL")}}})});
/* ******** */
(function(g){var h=window.AmazonUIPageJS||window.P,k=h._namespace||h.attributeErrors,a=k?k("PREXWebAppBuzzAssets@labelPage","PREXWebApp"):h;a.guardFatal?a.guardFatal(g)(a,window):a.execute(function(){g(a,window)})})(function(g,h,k){g.when("A","mash-url-utils","url-utils","csm-publisher").execute("print-label-handler",function(a,b,c,d){function f(){d.incrementCsmCount("PREX:LabelPage:PrintButtonClicked:Browser");h.print&&h.print()}a.on.ready(function(){h.print||a.$(".print-label-button").hide()});
a.on.ready(function(){var e=a.state("label-page-state");e&&"true"===e.shouldTriggerPrintAction&&f()});a.$("body").delegate("#print-label-button-browser","click",f);a.$("body").delegate("#print-label-button-app","click",function(a){a.preventDefault();d.incrementCsmCount("PREX:LabelPage:PrintButtonClicked:App");a=c.getUrlWithQueryParams(h.location,{printLabel:"true",ref_:"redir_frm_app"});b.goToUrl(a)})});"use strict";g.when("A","ready").register("label-error-utils",function(a){function b(a){return"true"===
a.dataset.reloadRequired}function c(a){return a.dataset.mainSource===a.dataset.shadowSource}var d={};return{isMainSourceReload:function(a,e){return b(e)&&d[a]===k&&""!==e.src?(d[a]=0,!0):!1},prepareFallback:function(a,e){b(e)||d[a]!==k||(d[a]=0)},isReloadRequired:b,isAllowedToFallback:function(a,b){return!c(b)&&0===d[a]},areBothImageSourcesSame:c,isShadowSourceReloadRequired:function(a){return 1===d[a]},incrementNumOfAttemptsToLoadShadowSourceImage:function(a){d[a]++}}});"use strict";g.when("A","url-utils",
"csm-publisher","prex-logger","label-error-utils").execute(function(a,b,c,d,f){function e(a,b){setTimeout(function(){c.incrementCsmCount("PREX:LabelPage:ImageLoadFailure:S3:ShadowSource:Reload");f.incrementNumOfAttemptsToLoadShadowSourceImage(a);b.src=b.dataset.shadowSource},5E3)}function u(a){setTimeout(function(){var e=b.getUrlWithQueryParams(h.location,{imageErrorReload:"true"});f.areBothImageSourcesSame(a)?c.incrementCsmCount("PREX:LabelPage:ImageLoadFailure:S3:MainSource:Reload"):(d.error("Alexandria Url: ["+
a.dataset.mainSource+"]","alexandria_url"),c.incrementCsmCount("PREX:LabelPage:ImageLoadFailure:Alexandria:MainSource:Reload"));h.location.replace(e)},5E3)}a.$(".return-label-image").each(function(a,b){b.onerror=function(b){b=b.target;f.prepareFallback(a,b);if(f.isMainSourceReload(a,b))if(b.src=b.src,f.incrementNumOfAttemptsToLoadShadowSourceImage(a),f.areBothImageSourcesSame(b))c.incrementCsmCount("PREX:LabelPage:ImageLoadFailure:S3:MainSource:Load");else{var g=b.dataset.mainSource.length;d.error("Alexandria Url: ["+
b.dataset.mainSource+"], length:"+g,"alexandria_url");c.incrementCsmCount("PREX:LabelPage:ImageLoadFailure:Alexandria:MainSource:Load:"+(0===g?"EMPTY":300>g?"URL":"STREAM"))}else f.isReloadRequired(b)?u(b):f.isAllowedToFallback(a,b)?(f.incrementNumOfAttemptsToLoadShadowSourceImage(a),b.src=b.dataset.shadowSource):f.isShadowSourceReloadRequired(a)?e(a,b):(b.onerror=null,f.areBothImageSourcesSame(b)?c.incrementCsmCount("PREX:LabelPage:ImageLoadFailure:S3:MainSource:Failure"):(d.error("Alexandria byte Url: ["+
b.dataset.mainSource+"]","alexandria_byte_url"),c.incrementCsmCount("PREX:LabelPage:ImageLoadFailure:Alexandria:Failure")))};b.src=b.dataset.mainSource})});"use strict";g.when("dhl-links-metric-utils").execute("label-page-dhl-links-metric-publisher",function(a){a.registerDhlLinkClickEventHandlers("labelPage")});"use strict";g.register("email-address-validator",function(){var a=/^\S+@\S+\.\S+$/;return{validateAndGetEmailAddresses:function(b){b=b.map(function(a){return a.trim()});var c=b.filter(function(b){return!a.test(b)});
return{areAllEmailIdsValid:0===c.length,emailIds:b,invalidEmailIds:c}}}});"use strict";g.when("A","csm-publisher").execute(function(a,b){a.on("a:popover:show:linkToShareLabelPopoverContent",function(){b.incrementCsmCount(b.getCSMPublisherPrefix()+":LabelPage:LinkToShareLabel:Shown")});a.on("a:popover:ajaxFail:linkToShareLabelPopoverContent",function(){b.incrementCsmCount(b.getCSMPublisherPrefix()+":LabelPage:LinkToShareLabel:FailedToLoad")})});"use strict";g.when("email-address-validator").register("send-label-to-friend-input-validator",
function(a){return{getValidatedInput:function(b,c,d){b=b.trim().replace(/,$/g,"").split(",").filter(function(a){return 0<a.trim().length});if(0===b.length)return{isValid:c,invalidReason:c?"":"invalidEmailInput",emailIds:[]};c=a.validateAndGetEmailAddresses(b);b=!0;var f="";c.areAllEmailIdsValid?c.emailIds.length<=d||(b=!1,f="emailLimitExceeded"):(b=!1,f="invalidEmailInput");return{isValid:b,invalidReason:f,invalidInput:c.invalidEmailIds,emailIds:c.emailIds}}}});"use strict";g.register("send-label-to-self-input-validator",
function(){return{getValidatedInput:function(){return{isValid:!0,invalidReason:k,emailIds:[]}}}});"use strict";g.when("A","display-utils","share-label-constants","share-label-popup-utils","share-label-request-adapter","csm-publisher","prex-logger","redirection-utils","csrf-utils","ready").execute(function(a,b,c,d,f,e,g,r,t){function q(b){a.post("/spr/returns/label/share/"+b.contractId,{headers:t.addCsrfHeader({}),params:b.params,indicator:a.$("#loading-email-spinner"),success:function(e){var c=b.emailIds;
200===e.statusCode?(d.showSuccessSectionAndHideOthers(),d.unsetErrorAriaAttributesOnShareLabelTextArea()):0<=a.indexOfArray([400,401,403],e.statusCode)?""!==e.redirectUrl?r.setRedirectionUrl(e.redirectUrl):n(c):(d.showErrorSendingMailAlertAndHideOthers(),d.unsetErrorAriaAttributesOnShareLabelTextArea())},error:function(){var a=b.contractId;d.showErrorSendingMailAlertAndHideOthers();d.unsetErrorAriaAttributesOnShareLabelTextArea();g.error("Failed to Share Label through Mail for Contract: "+a);e.incrementCsmCount(e.getCSMPublisherPrefix()+
":ShareLabelRequest:Failed")}})}function n(b){e.incrementCsmCount(e.getCSMPublisherPrefix()+":ShareLabelRequest:FailedDueToIllegalArguments");a.$("#invalid-email").html(p(b));d.showInvalidEmailErrorAlertAndHideOthers();d.setErrorAriaAttributesOnShareLabelTextArea(c.INVALID_EMAIL);d.focusOnShareLabelTextArea()}function p(a){return a!==k&&0!==a.length?a.reduce(function(a,b){return a+", "+b}):""}function m(){var b=a.$("#"+c.REMAINING_CHARS_MESSAGE_ELEMENT_ID).text();a.$("#"+c.REMAINING_CHARS_MESSAGE_ANNOUNCEMENT_ELEMENT_ID).text(b)}
var l=null;a.$("body").delegate("#button-share","click",function(){var a=f.adapt();a.isValid?(b.showElementById("loading-email-spinner"),q(a)):"emailLimitExceeded"===a.inValidReason?(d.showEmailsLimitExceededErrorAlertAndHideOthers(),d.setErrorAriaAttributesOnShareLabelTextArea(c.EMAIL_LIMIT_EXCEEDED),d.focusOnShareLabelTextArea()):n(a.invalidInput)});a.$("#cancel-sharelabel-button").click(function(){d.hideLabelPagePopover("shareLabelPopoverContent")});a.on("a:popover:afterHide:shareLabelPopoverContent",
function(){d.resetShareLabelPopup();d.unsetErrorAriaAttributesOnShareLabelTextArea()});a.$("body").delegate("#"+c.SHARE_EMAIL_TO_FRIENDS_TEXT_AREA_ID,"input propertychange",function(b){var e=a.$(b.currentTarget);b=e.attr("maxLength");e=e.val().length;a.$("#"+c.SHARE_EMAIL_CHAR_COUNT_ELEMENT_ID).text(b-e);l&&h.clearTimeout(l);l=h.setTimeout(m,2E3)})});"use strict";g.when("A","share-label-constants","share-label-popup-device-utils","display-utils","ready").register("share-label-popup-utils",function(a,
b,c,d){function f(b,c){a.each(c,function(a){d.hideElementById(a)});a.each(b,function(a){d.showElementById(a)})}return{hideLabelPagePopover:function(a){c.hideLabelPagePopover(a)},divsToBeShownAndHidden:f,focusOnShareLabelTextArea:function(){a.$("#"+b.SHARE_EMAIL_TO_FRIENDS_TEXT_AREA_ID).focus()},setErrorAriaAttributesOnShareLabelTextArea:function(e){var c=a.$("#"+b.SHARE_EMAIL_TO_FRIENDS_TEXT_AREA_ID);b.INVALID_EMAIL===e?(c.attr("aria-describedby",b.INVALID_EMAIL_ALERT_ID),c.attr("aria-invalid",!0)):
b.EMAIL_LIMIT_EXCEEDED===e&&(c.attr("aria-describedby",b.EMAIL_LIMIT_EXCEEDED_ALERT_ID),c.attr("aria-invalid",!0))},unsetErrorAriaAttributesOnShareLabelTextArea:function(){var e=a.$("#"+b.SHARE_EMAIL_TO_FRIENDS_TEXT_AREA_ID);"true"===e.attr("aria-invalid")&&(e.removeAttr("aria-describedby"),e.removeAttr("aria-invalid"))},showEmailsLimitExceededErrorAlertAndHideOthers:function(){f(["share-label-popover-input-section","error-exceeded-limit"],["share-label-success-message","error-sending-email","error-invalid-email"])},
showErrorSendingMailAlertAndHideOthers:function(){f(["share-label-popover-input-section","error-sending-email"],["share-label-success-message","error-invalid-email","error-exceeded-limit"])},showInvalidEmailErrorAlertAndHideOthers:function(){f(["share-label-popover-input-section","error-invalid-email"],["share-label-success-message","error-sending-email","error-exceeded-limit"])},resetShareLabelPopup:function(){f(["share-label-popover-input-section"],["error-sending-email","error-invalid-email","share-label-success-message",
"error-exceeded-limit"])},showSuccessSectionAndHideOthers:function(){f(["share-label-success-message"],["share-label-popover-input-section","error-invalid-email","error-sending-email","error-exceeded-limit"])}}});"use strict";g.when("ready").register("share-label-constants",function(){return{SHARE_EMAIL_TO_FRIENDS_TEXT_AREA_ID:"share-email",INVALID_EMAIL_ALERT_ID:"invalid-email-error-alert",EMAIL_LIMIT_EXCEEDED_ALERT_ID:"email-limit-exceeded-error-alert",SHARE_EMAIL_CHAR_COUNT_ELEMENT_ID:"share-email-char-count",
REMAINING_CHARS_MESSAGE_ELEMENT_ID:"remaining-characters-message",REMAINING_CHARS_MESSAGE_ANNOUNCEMENT_ELEMENT_ID:"remaining-characters-message-announcement",INVALID_EMAIL:"INVALID_EMAIL",EMAIL_LIMIT_EXCEEDED:"EMAIL_LIMIT_EXCEEDED"}});"use strict";g.when("A","a-modal","ready").register("share-label-popup-device-utils",function(a,b){return{hideLabelPagePopover:function(a){b.get(a).hide()}}});"use strict";g.when("A","share-label-constants","send-label-to-friend-input-validator","send-label-to-self-input-validator",
"ready").register("share-label-request-adapter",function(a,b,c,d){function f(a){return a.isValid&&0<a.emailIds.length?a.emailIds.reduce(function(a,b){return a+";"+b})+";":""}return{adapt:function(){var e=a.$("#"+b.SHARE_EMAIL_TO_FRIENDS_TEXT_AREA_ID).val(),g=a.$("#send-to-self-checkbox").is(":checked"),h=a.$("#email-recipient-selection").data("emailsLimit"),k=a.$("#share-label-popover-input-section").data("contractId");"emailSendToSelf"===a.$("#email-recipient-selection").find(".a-accordion-active").data("aAccordionRowName")?
(g=!0,e=d.getValidatedInput()):e=c.getValidatedInput(e,g,h);var h=e.isValid,q=e.invalidReason,n=e.invalidInput,p=f(e),m;m=(m=a.$("#share-label-email-message").data("fixedEmailMessage"))?m:encodeURIComponent(a.$("#custom-message").val());return{isValid:h,inValidReason:q,invalidInput:n,params:{emailTo:p,emailMessage:m,sendToSelf:g,contractID:k,customerID:a.$("#share-label-popover-input-section").data("customerId"),labelLinkExpiryDate:encodeURIComponent(a.$("#share-label-popover-input-section").data("labelLinkExpiry"))},
emailIds:e.emailIds,contractId:k}}}});"use strict";g.when("A","share-label-popup-utils","csrf-utils","csm-publisher","prex-logger","prex-event-publisher","page-state-utils","ready").execute(function(a,b,c,d,f,e,g){function h(){var a={};a.addressId=l.data("addressId");a.contractId=l.data("contractId");return{requestParams:a,contractId:a.contractId}}function k(){var b=l.data("orderIds"),c=l.data("contractId"),d=g.getValue("prexInstrumentationPageData","subPageType"),f=l.data("fulfillmentChannel"),b=
a.map(b,function(a){return{eventName:"SendMailButtonClicked",contractId:c,orderId:a,subPageType:d,dataKey:"fulfillmentChannel",dataValue:f}});e.publishEventsGroup(b)}function q(a){a.requestSuccessful?(p(),b.divsToBeShownAndHidden(["post-send-snail-mail-section"],["return-deadline-display",m()])):b.divsToBeShownAndHidden(["error-sending-snailmail","snail-mail-description-section"],["loading-spinner"])}function n(){b.divsToBeShownAndHidden(["error-sending-snailmail","snail-mail-description-section"],
["loading-spinner"]);f.error("Failed to RequestSnailMail for Contract: "+h().contractId);d.incrementCsmCount(d.getCSMPublisherPrefix()+":SnailMail:SetSnailRequest:Failed")}function p(){b.hideLabelPagePopover("snailMailPopoverContent")}function m(){if(0<a.$("#snail-mail-secondary-view-trigger").length)return"snail-mail-secondary-view-trigger";if(0<a.$("#snail-mail-modal-trigger").length)return"snail-mail-modal-trigger"}var l=a.$("#snail-mail-description-section");a.$("body").delegate("#request-snailmail-button",
"click",function(){k();d.incrementCsmCount(d.getCSMPublisherPrefix()+":SnailMail:SendSnailRequest:Clicked");b.divsToBeShownAndHidden(["loading-spinner"],["snail-mail-description-section"]);a.post(a.$("#SnailMailRequestUrl").val(),{headers:c.addCsrfHeader({}),params:h().requestParams,success:q,error:n})});a.$("body").delegate("#cancel-snailmail-button","click",p)})});
/* ******** */
(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("PREXWebAppBuzzAssets@ledger","PREXWebApp"):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
(function(b){var c=window.AmazonUIPageJS||window.P,d=c._namespace||c.attributeErrors,a=d?d("PREXWebAppBuzzAssets@confirmationPage","PREXWebApp"):c;a.guardFatal?a.guardFatal(b)(a,window):a.execute(function(){b(a,window)})})(function(b,c,d){b.when("A","display-utils").execute(function(a,b){a.$("body").delegate("#primary-label-action-button","click",function(){b.hideElementById("primary-label-action-pending-section");b.showElementById("primary-label-action-completed-section")})});"use strict";b.when("dhl-links-metric-utils").execute("confirmation-page-dhl-links-metric-publisher",
function(a){a.unregisterDhlLinkClickEventHandlers("labelPage");a.registerDhlLinkClickEventHandlers("confirmationPage")});"use strict";b.when("A").execute(function(a){a.$("body").delegate(".package-group-instructions-heading","keydown",function(b){32===b.keyCode&&(b.preventDefault(),a.$(b.currentTarget).click())})});"use strict";b.when("A","ready").execute(function(a){(a=a.$("#email-recipient-selection"))&&!a.attr("role")&&a.attr("role","group")})});
/* ******** */
